<?php
$flash = $this->flashMessenger();
echo $flash->render('error', array('alert', 'alert-dismissible', 'alert-danger'));
//echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
//echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));

$title = 'Usuários';
$this->headTitle($title);
?>

<div class="row">
    <h1><?= $this->escapeHtml($title) ?></h1>

    <table class="table table-bordered table-striped table-hover">
        <tr>
            <th>Nome</th>
            <th>Login</th>
            <th>Status</th>
            <th>&nbsp;</th>
        </tr>

        <?php foreach ($usuarios as $usuario) : ?>
            <tr>
                <td><?php echo $this->escapeHtml($usuario->getRealName()); ?></td>
                <td><?php echo $this->escapeHtml($usuario->getUsername()); ?></td>
                <td><?php echo $this->escapeHtml($usuario->getLabelStatus()); ?></td>
                <td>
                    <a class="btn btn-info" href="<?php echo $this->url('usuario', array('action' => 'edit', 'id' => $usuario->getId()));
            ?>"><span class="glyphicon glyphicon-pencil"></span>&nbsp;Editar</a>
                    <a class="btn <?php if ($usuario->getStatus()): ?>btn-success<?php else: ?>btn-danger<?php endif ?>" href="<?php echo $this->url('usuario', array('action' => 'changeStatus', 'id' => $usuario->getId()));
            ?>"><span class="glyphicon <?php if ($usuario->getStatus()): ?>glyphicon-ok<?php else: ?> glyphicon-remove<?php endif ?>"></span>&nbsp;Ativar/Desativar Usuário</a>
                </td>
            </tr>
        <?php endforeach; ?>

        <tr>
            <td colspan="5">  <a class="btn btn-success pull-right" href="<?php echo $this->url('usuario', array('action' => 'add')); ?>"><span class="glyphicon glyphicon-plus-sign"></span>&nbsp;
                    Adicionar novo usuário&nbsp;<span class="glyphicon glyphicon-user"></span></a></td>
        </tr>
    </table>

    <?php
    echo $this->paginationControl(
            $usuarios, 'sliding', 'partial/paginator.phtml', array(
        'route' => 'usuario'
            )
    );
    ?>

</div>
