<?php
$flash = $this->flashMessenger();
echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
//echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
//echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
?>

<div class="row">
    Página Inicial
</div>
